debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cli?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  shell:
    interactive:
      enabled: true

server:
  port: 9003